<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyVersion>1.2026.0922.0</AssemblyVersion>
    <FileVersion>1.2026.0922.0</FileVersion>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>Resources\Icons\NatsROS图标_15620-11种尺寸.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TopicMonitorItem.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="NatsROS图标.png" />
    <None Remove="UI\ThemedSplashScreen\ats256x256.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Icons\NatsROS图标_15620-11种尺寸.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.Images" Version="24.2.7" />
    <PackageReference Include="devexpress.wpf.charts" Version="24.2.7" />
    <PackageReference Include="devexpress.wpf.diagram" Version="24.2.7" />
    <PackageReference Include="devexpress.wpf.grid.core" Version="24.2.7" />
    <PackageReference Include="devexpress.wpf.layoutcontrol" Version="24.2.7" />
    <PackageReference Include="devexpress.wpf.propertygrid" Version="24.2.7" />
    <PackageReference Include="DevExpress.Wpf.Themes.All" Version="24.2.7" />
    <PackageReference Include="MessagePack" Version="3.1.8" />
    <PackageReference Include="NATS.Net" Version="2.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Framework_Core\NatsROS.Core\NatsROS.Core.csproj" />
    <ProjectReference Include="..\..\Framework_Core\NatsROS.Hosting\NatsROS.Hosting.csproj" />
    <ProjectReference Include="..\..\Framework_Core\NatsROS.Messages\NatsROS.Messages.csproj" />
    <ProjectReference Include="..\NatsROS.BehaviorTree\NatsROS.BehaviorTree.csproj" />

  </ItemGroup>

  <ItemGroup>
    <Resource Include="NatsROS图标.png" />
    <Resource Include="UI\ThemedSplashScreen\ats256x256.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Plugins\BehaviorTree\BehaviorTreeView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Plugins\MesReport\MesReportView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UI\Dialogs\PluginManagerDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
