<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<!-- 【版本号控制】：跟着机型业务走 -->
		<AssemblyVersion>1.2026.0922.1</AssemblyVersion>
		<FileVersion>1.2026.0922.1</FileVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- 引入 DevExpress 和 第三方库，绝对禁止拷贝到沙盒！ -->
		<PackageReference Include="devexpress.wpf.controls" Version="24.2.7" ExcludeAssets="runtime" />
		<PackageReference Include="devexpress.wpf.charts" Version="24.2.7" ExcludeAssets="runtime" />
		<PackageReference Include="devexpress.wpf.diagram" Version="24.2.7" />
		<PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" ExcludeAssets="runtime" />
		<PackageReference Include="MessagePack" Version="3.1.8" ExcludeAssets="runtime" />
		<PackageReference Include="NATS.Net" Version="2.7.3" ExcludeAssets="runtime" />
	</ItemGroup>

	<ItemGroup>
		<!-- 引入 NatsROS 核心库，绝对禁止拷贝！ -->
		<ProjectReference Include="..\..\..\NatsROS_Platform\Framework_Core\NatsROS.Core\NatsROS.Core.csproj">
			<Private>false</Private>
		</ProjectReference>
		<ProjectReference Include="..\..\..\NatsROS_Platform\Framework_Core\NatsROS.Messages\NatsROS.Messages.csproj">
			<Private>false</Private>
		</ProjectReference>
		<ProjectReference Include="..\..\00_Messages\ScrewMachine.Messages\ScrewMachine.Messages.csproj">
		  <Private>False</Private>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="DigitalTwin\DigitalTwinView.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="HalConsole\HalConsoleView.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="PointStudio\PointStudioView.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	</ItemGroup>
</Project>